import test from 'node:test';
import assert from 'node:assert/strict';
import {computeStatus} from '../src/domain.js';
import {imgwHydroAdapter,imgwMeteoAdapter,parseImgwHydro,parseImgwMeteo} from '../src/imgw-adapter.js';

const now=new Date('2026-09-23T10:00:00Z');
const hydro=JSON.stringify([{opublikowano:'2026-05-17 08:45:07','stopień':'-1',data_od:'2026-05-17 08:45:56',data_do:'9999-12-31 23:59:59',prawdopodobienstwo:'90',numer:'31',biuro:'Biuro Prognoz Hydrologicznych we Wrocławiu',zdarzenie:'Susza hydrologiczna',przebieg:'Utrzymywanie się przepływów poniżej SNQ.',komentarz:'Ostrzeżenie hydrologiczne.',obszary:[{wojewodztwo:'wielkopolskie',opis:'wielkopolskie, Kanał Mosiński, susza hydrologiczna',kod_zlewni:['Z_P_WP_1856']}]}]);
const meteo=JSON.stringify([{nazwa_zdarzenia:'Burze',stopien:'2',prawdopodobienstwo:'80',obowiazuje_od:'2026-09-23 13:00:00',obowiazuje_do:'2026-09-23 23:00:00',opublikowano:'2026-09-23 09:00:00',tresc:'Prognozowane są burze z silnymi opadami i porywami wiatru.',komentarz:'Ostrzeżenie może być aktualizowane.',biuro:'Centralne Biuro Prognoz Meteorologicznych',numer:'73',teryt:['0401','0461']}]);

test('IMGW hydro maps public JSON without inventing geometry',()=>{const [e]=parseImgwHydro(hydro,now);assert.equal(e.eventType,'WEATHER');assert.equal(e.severity,'NORMAL');assert.equal(e.lifecycle,'ACTIVE');assert.equal(e.verification,'CONFIRMED');assert.equal(e.officialWarning,true);assert.deepEqual(e.regions,['30']);assert.equal(e.geometry,null);assert.equal(e.areaPrecision,'PROVINCE_SUBSET');assert.equal(e.sources[0].id,'IMGW_HYDRO');assert.match(e.locationText??'',/Kanał Mosiński/);});
test('IMGW meteo derives province from TERYT and preserves validity',()=>{const [e]=parseImgwMeteo(meteo,now);assert.equal(e.severity,'HIGH');assert.equal(e.lifecycle,'SCHEDULED');assert.deepEqual(e.regions,['04']);assert.equal(e.areaPrecision,'PROVINCE_SUBSET');assert.equal(e.geometry,null);assert.match(e.description,/Prawdopodobieństwo: 80%/);});
test('IMGW exact no-products payload is a safe empty set',()=>{const empty='{"status":false,"message":"No products were found"}';assert.deepEqual(parseImgwMeteo(empty,now),[]);assert.deepEqual(parseImgwHydro(empty,now),[]);});
test('IMGW parser fails closed on unknown TERYT and unsupported warning degree',()=>{const badRegion=JSON.parse(meteo);badRegion[0].teryt=['9901'];assert.throws(()=>parseImgwMeteo(JSON.stringify(badRegion),now),/IMGW_UNKNOWN_REGION/);const badLevel=JSON.parse(hydro);badLevel[0]['stopień']='7';assert.throws(()=>parseImgwHydro(JSON.stringify(badLevel),now),/IMGW_WARNING_LEVEL_INVALID/);});
test('IMGW adapters expose complete active-warning coverage independently',async()=>{const a=await imgwMeteoAdapter.sync({now,fetchText:async()=>meteo});const b=await imgwHydroAdapter.sync({now,fetchText:async()=>hydro});assert.equal(a.complete,true);assert.equal(b.complete,true);assert.equal(a.coverage,'ACTIVE_WARNINGS');assert.equal(b.coverage,'ACTIVE_WARNINGS');});
test('active tier-1 IMGW warning participates in regional status',()=>{const [event]=parseImgwMeteo(meteo,new Date('2026-09-23T12:00:00Z'));const health={id:'IMGW_METEO',name:'IMGW',url:'https://danepubliczne.imgw.pl/api/data/warningsmeteo',state:'HEALTHY' as const,lastSuccess:'2026-09-23T12:00:00Z',lastFailure:null,lastItemTime:event.publishedAt,failureCount:0,responseTime:20,maxAgeSeconds:900,complete:true,enabled:true,coverage:'ACTIVE_WARNINGS' as const,pagesFetched:1};const status=computeStatus([event],[health],'04',new Date('2026-09-23T12:30:00Z'));assert.equal(status.hazardLevel,'CAUTION');assert.deepEqual(status.supportingEventIds,[event.id]);});
