import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import * as cheerio from 'cheerio';
import {parseLevelsArticle,parseLevelsIndex,securityLevelsAdapter,LEVELS_INDEX} from '../src/security-level-adapter.js';
import {securityLevels,securityLevelStatus} from '../src/security-level.js';import {computeStatus} from '../src/domain.js';import {Store,openDb} from '../src/store.js';import {initializeSources,ingest} from '../src/adapters.js';import {buildApp} from '../src/app.js';
const html=readFileSync('test/fixtures/levels-current.html','utf8'),index=readFileSync('test/fixtures/levels-index.html','utf8'),url='https://www.gov.pl/web/rcb/przedluzenie-obowiazywania-stopni-alarmowych-do-30-listopada-2026-r',now=new Date('2026-09-20T12:00:00Z');
const parse=(h=html)=>parseLevelsArticle(h,url,now);
function single(){const $=cheerio.load(html);$('.editor-content li').slice(1).remove();return $.html();}
function finalIndex(){const $=cheerio.load(index);$('#js-pagination-page-next').remove();return $.html();}
const fetchFixture=async(u:string)=>u===LEVELS_INDEX?finalIndex():html;
for(const level of ['ALFA','BRAVO','CHARLIE','DELTA'])for(const crp of [false,true])test(`recognizes ${level}${crp?'-CRP':''}`,()=>{const rows=parse(single().replace('(stopień BRAVO)',`(stopień ${level}${crp?'-CRP':''})`));assert.equal(rows.length,1);assert.equal(rows[0].securityLevel!.type,crp?'CRP':'PHYSICAL');assert.equal(rows[0].securityLevel!.level,level);});
test('real fixture: four parallel scopes, physical BRAVO + BRAVO-CRP; no danger escalation',()=>{const events=parse(),levels=securityLevels(events,'PL',now);assert.equal(levels.length,4);assert.equal(securityLevels(events,'04',now).length,3);assert.deepEqual(levels.filter(s=>s.scope==='NATIONAL').map(s=>s.type).sort(),['CRP','PHYSICAL']);assert.ok(levels.some(s=>s.scope==='INFRASTRUCTURE'&&s.area.includes('PKP')));assert.ok(levels.some(s=>s.scope==='EXTRATERRITORIAL_INFRASTRUCTURE'&&s.regions.length===0));assert.equal(computeStatus(events,[],'PL',now).hazardLevel,'UNKNOWN');});
test('regional scope is limited and never expands province-subset description',()=>{const levels=parse(single().replace('na całym terytorium Rzeczypospolitej Polskiej','na obszarze województwa kujawsko-pomorskiego'));assert.deepEqual(levels[0].regions,['04']);assert.equal(securityLevels(levels,'14',now).length,0);assert.equal(securityLevels(levels,'04',now).length,1);});
test('validity uses Warsaw DST, inclusive end minute and dynamic expiry',()=>{const events=parse();assert.equal(events[0].validFrom,'2026-08-31T22:00:00.000Z');assert.equal(events[0].validTo,'2026-11-30T22:59:59.999Z');assert.equal(securityLevels(events,'PL',new Date('2026-11-30T22:59:59Z')).length,4);assert.equal(securityLevels(events,'PL',new Date('2026-11-30T23:00:00Z')).length,0);assert.equal(securityLevels(events,'PL',new Date('2026-08-30')).length,0);});
test('detects empty/error/changed HTML, unknown dates and cancellation requiring review',()=>{for(const bad of ['', '<html>Forbidden</html>',html.replaceAll('editor-content','changed'),html.replaceAll('30 listopada','31 listopada'),html.replaceAll('BRAVO','ECHO'),html.replaceAll('Przedłużenie obowiązywania','Odwołanie')])assert.throws(()=>parse(bad));assert.throws(()=>parseLevelsIndex('<article></article>'));assert.ok(parseLevelsIndex(index).links.some(l=>l.url===url));});
test('deduplicates repeated orders; rejects conflicting duplicate',()=>{const $=cheerio.load(single());$('.editor-content ul').append($('.editor-content li').first().clone());assert.equal(parse($.html()).length,1);$('.editor-content li').last().html($('.editor-content li').last().html()!.replace('30 listopada','29 listopada'));assert.throws(()=>parse($.html()),/CONFLICTING/);});
test('idempotence, end-date correction and extension produce audited revisions',async()=>{const db=openDb(undefined,':memory:'),store=new Store(db);await store.init();try{for(const e of parse())await store.put(e);for(const e of parse())await store.put(e);assert.equal((await store.timeline(parse()[0].id)).length,1);const changed=parse(html.replaceAll('30 listopada','29 listopada'));for(const e of changed)await store.put(e);assert.equal((await store.timeline(changed[0].id)).length,2);for(const e of parse(html.replaceAll('30 listopada','31 grudnia')))await store.put(e);assert.equal((await store.timeline(changed[0].id)).length,3);assert.equal((await store.get(changed[0].id))!.securityLevel!.validTo,'2026-12-31T22:59:59.999Z');}finally{await db.close();}});
test('source failure/invalid response/empty data preserve last good copy and never GREEN',async()=>{const db=openDb(undefined,':memory:'),store=new Store(db);await store.init();await initializeSources(store);try{const adapter={...securityLevelsAdapter,minSyncIntervalSeconds:0};await ingest(store,[adapter],fetchFixture);const good=(await store.health()).find(s=>s.id==='LEVELS')!;assert.equal(good.state,'HEALTHY');for(const fetcher of [async()=>{throw new Error('SOURCE_HTTP_503');},async()=>'<html>error</html>',async()=>finalIndex().replaceAll('Przedłużenie obowiązywania stopni alarmowych','Zwykły komunikat')]){await ingest(store,[adapter],fetcher);const health=await store.health(),h=health.find(s=>s.id==='LEVELS')!;assert.equal(h.state,'BROKEN');assert.equal(h.lastSuccess,good.lastSuccess);assert.ok(h.lastFailure);assert.equal((await store.events()).length,4);assert.equal(securityLevelStatus(await store.events(),health,'PL',now).securityLevelsStatus,'STALE');assert.equal(computeStatus(await store.events(),health,'PL',now).hazardLevel,'UNKNOWN');}const app=await buildApp(store);try{const status=(await app.inject('/status?regionId=04')).json();assert.equal(status.poland.securityLevels.length,4);assert.equal(status.region.securityLevels.length,3);assert.equal(status.securityLevelsStatus,'STALE');const snap=(await app.inject('/v1/snapshot?regionId=04')).json();assert.equal(snap.securityLevels.length,3);assert.equal(snap.events.length,0);}finally{await app.close();}}finally{await db.close();}});
